name: Create artifact

on: [workflow_dispatch]

jobs:
  create_build_artifact:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc g++ gfortran ninja-build git cmake liblapack-dev pkg-config --install-recommends -y

      - uses: actions/checkout@v4
        with:
          ref: 3.6.3

      - name: Build casadi
        run: |
          mkdir -p casadi_install
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/casadi_install
          cd ..
          cmake --build build
          cmake --install build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: casadi_v3.6.3
          path: casadi_install
          overwrite: true
          if-no-files-found: error
